import type { Metadata } from "next";
import { Sidebar } from "./components/Sidebar";
import styles from './styles.module.scss';


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="container">
            <div className={styles.profileContainer}>
                <Sidebar />
                <div className={styles.profileContent}>
                    {children}
                </div>
            </div>
        </div>
    );
}
